name: Cucumber Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.2.0

    - name: Set up JDK 11
      uses: actions/setup-java@v4.4.0
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Run tests
      run: mvn clean test

    - name: Upload Cucumber report
      uses: actions/upload-artifact@v4.4.0
      with:
        name: cucumber-report
        path: target/cucumber-reports

    - name: Zip Cucumber reports
      run: |
        
        mvn test -Dcucumber.plugin="json:target/cucumber-report.json"
        

    - name: Upload zipped report
      uses: actions/upload-artifact@v4.4.0
      with:
        name: zipped-cucumber-report
        path: target/cucumber-reports.zip
